# Rule fragment only: define a PROXY policy/group in your profile.
[Rule]
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/private.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/lan.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/proxy.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/cn.list,DIRECT
FINAL,PROXY
