# Rule fragment only: define PROXY, AI and APPLE policy/groups in your profile.
[Rule]
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/private.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/lan.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/wan-com.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/futu-broker.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/ai.list,AI
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/apple.list,APPLE
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/proxy.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/shadowrocket/cn.list,DIRECT
FINAL,PROXY
