# Import and activate this complete account configuration.
[General]
dns-server = system
dns-direct-system = true
dns-direct-fallback-proxy = false
ipv6 = false
block-quic = always-allow
udp-policy-not-supported-behaviour = REJECT

[Proxy]
${PROXIES}

[Proxy Group]
PROXY = select${PROXY_GROUP_OPTIONS}
