#!MANAGED-CONFIG ${MANAGED_URL} interval=43200 strict=false
# DNS for proxied domains is resolved remotely by the selected proxy.
[General]
loglevel = notify
ipv6 = false
dns-server = system
udp-policy-not-supported-behaviour = REJECT
exclude-simple-hostnames = true

[Proxy]
${PROXIES}

[Proxy Group]
PROXY = select, ${PROXY_NAMES}


