# Rule fragment only: define PROXY, AI and APPLE policy groups in your Loon profile.
[Rule]
FINAL,PROXY

[Remote Rule]
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/private.list, policy=DIRECT, tag=private, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/lan.list, policy=DIRECT, tag=lan, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/wan-com.list, policy=PROXY, tag=wan-com, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/futu-broker.list, policy=PROXY, tag=futu-broker, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/ai.list, policy=AI, tag=ai, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/apple.list, policy=APPLE, tag=apple, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/proxy.list, policy=PROXY, tag=proxy, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/direct.list, policy=DIRECT, tag=direct, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/telegram.list, policy=PROXY, tag=telegram, enabled=true
https://raw.githubusercontent.com/mercer08/proxy-rules/release/loon/cn.list, policy=DIRECT, tag=cn, enabled=true
