# Rule fragment only: define a PROXY policy/group in your profile.
[Rule]
DOMAIN-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/private.domainset,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/lan.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/lan-com.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/wan-com.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/futu-broker.list,PROXY
DOMAIN-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/reject.domainset,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/proxy.domainset,PROXY
DOMAIN-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/direct.domainset,DIRECT
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/mercer08/proxy-rules/release/surge/cn.list,DIRECT
FINAL,PROXY
